# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use official Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy application files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Expose MCP server over stdio (no ports needed)

# Default command to run the MCP server
CMD ["python", "apple_mcp.py"]
